### ISSUE TITLE
Include BeeKeeb's Smiling Orca

### ISSUE THREAD

**Issue by kartsims** [namnlos-io/choc_keycaps#2]
Hey there, thanks for this great repo! 

It could be nice to include those as well: https://www.thingiverse.com/thing:5425764

**Comment by janlindblom** [comment]
Oh hadn't seen them released outside of the beekeeb store before now! 

Will definitely include them too, been wanting to try them myself and I just so happen to have a spool of nylon filament on the shelf 😊

I made the repo for myself to keep track of keycaps I found and tried out, happy to see other people find it useful!

**Comment by janlindblom** [comment]
Added Smiling Orca!
